[package]
name = "opentools"
version = "0.1.1"
edition = "2024"
authors = ["Falsetry <falsetryczz@gmail.com>"]
license = "MIT"
description = "A rust toolbox that process OpenST chip data"
repository = "https://github.com/falsetry1514/opentools.git"
exclude = [
    "template.sh",
    "target/*",
    ".gitinore",
    "Cargo.lock"
]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
crossbeam = "0.8.4"
dashmap = "6.1.0"
flate2 = { version = "1.1.1", features = ["zlib-rs"] }
indicatif = "0.18.0"
rayon = "1.10.0"
regex = "1.11.1"
rust-htslib = "0.51.0"
seq_io = "0.3.4"
sysinfo = "0.37.0"
thiserror = "2.0.17"
