[workspace]
authors = ["Falsetry <falsetryczz@Gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "opentools"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
opentools = "../rust/target/release/opentools"

[dependencies]
python = ">=3.12.11,<3.13"
pip = ">=25.1.1,<26"
star = { version = ">=2.7.11b,<3", channel = "bioconda" }
